django-learning/food/urls.py
from django.urls import path
from . import views
app_name="food"
urlpatterns = [
   path("",views.foodView,name="index"),
   path('<int:item_id>/',views.details,name='details'),
   path("item/",views.item),
   path("add/",views.create_item,name="create_item"),
   path("update/<int:item_id>/",views.update_item,name="update_item")
]

django-learning/myproject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("food/",include("food.urls"))
]

django-learning/food/models.py
from django.db import models

# Create your models here.

class Item (models.Model):

      def __str__(self):
            return f"{self.item_name} {self.item_desc}"
      
      item_name = models.CharField(max_length=200)
      item_desc=models.CharField(max_length=200)
      item_price=models.IntegerField()
      item_image=models.CharField(max_length=500,default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT27gTKHqKhHk3i-EiarE5Q9IND_awvKaKjxw&s")

django-learning/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
      class Meta:
            model=Item
            fields=['item_name','item_desc','item_price',"item_image"]

django-learning/food/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Item
from django.template import loader
from .forms import ItemForm

# View to list all items
def foodView(request):
    item_list = Item.objects.all()  # Get all items from the database
    # template = loader.get_template('food/index.html')  # Load the template
    print(item_list)
    context = {
        'item_list': item_list  # Pass item list to the template
    }
    # return HttpResponse(template.render(context, request))  # Render the template with context

    return render(request,"food/index.html",context)

# Simple test view
def item(request):
    return HttpResponse("<h1>this is an item view</h1>")


def details(request,item_id):
    item=Item.objects.get(pk=item_id)
    print(item)
    context={
        "item":item
    }
    return render(request,"food/details.html",context)


def create_item(request):
    form=ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("food:index")


    return render(request,"food/item_form.html",{'form':form})


def update_item(request,item_id):
    item=Item.objects.get(id=item_id)

    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")
    

    return render(request,"food/item_form.html",{"form":form,"data":item})

django-learning/food/templates/food/details.html
<ul>
  <li>{{item.id}}</li>
  <li>{{item.item_name}}</li>
  <li>{{item.item_desc}}</li>
</ul>

django-learning/food/templates/food/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/index.css' %}" />
  </head>
  <body>
    <ul>
      {% for item in item_list %}
      <img src="{{item.item_image}}" />
      <li>
        <a href="{% url 'food:details' item.id %}">
          {{ item.id }} --- {{ item.item_name }} --- {{ item.desc }}
        </a>
      </li>
      <li>{{item.item_price}}</li>
      {% endfor %}
    </ul>
  </body>
</html>

django-learning/food/templates/food/item_form.html
<form method="post">
  {% csrf_token %} {{form}}
  <button type="submit">submit</button>
</form>